name: CI
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
env:
  FC: ifort
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install ifort
        uses: ./
      - name: Test installation
        run: |
          ./scripts/test/test_install.sh /opt/intel/oneapi
      - name: Test compile and run program
        run: |
          ./scripts/test/test_compile.sh
  test_windows:
    name: Test (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install ifort
        uses: ./
      - name: Test installation
        run: |
          ./scripts/test/test_install.ps1 "C:\Program Files (x86)\Intel\oneAPI"
        env:
          VS_VER: vs2022
      - name: Test compile and run program
        run: |
          ./scripts/test/test_compile.ps1
        env:
          VS_VER: vs2022